cd ./LLaVA
aligned_path=base

deepspeed llava/train/train_mem_prefix.py --aligned_path ${aligned_path} \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-7b \
    --version v1 \
    --data_path ../prefixDS.json \
    --image_folder ./ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --audio_tower laion/clap-htsat-unfused \
    --mm_projector_type mlp2x_gelu \
    --modality image \
    --prefix True \
    --mm_vision_select_layer -2 \
    --tune_mm_mlp_adapter False \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ../expe/DALI_OT_ATT/models \
    --num_train_epochs 500 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
