CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

AUDIO_TOKEN_INDEX = -201
DEFAULT_AUDIO_TOKEN = "<audio>"
DEFAULT_AUDIO_PATCH_TOKEN = "<au_patch>"
DEFAULT_AU_START_TOKEN = "<au_start>"
DEFAULT_AU_END_TOKEN = "<au_end>"
AUDIO_PLACEHOLDER = "<audio-placeholder>"